import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:todo_list/home_page.dart';
import 'package:todo_list/theme_provider.dart';

void main() {
  runApp(const ProviderScope(child: TodoSheetApp()));
}

class TodoSheetApp extends ConsumerWidget {
  const TodoSheetApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // We 'watch' the providers. When their values change, this widget will rebuild.
    final themeMode = ref.watch(themeModeProvider);
    final accentColor = ref.watch(accentColorProvider);

    return MaterialApp(
      title: 'todo sheet',
      debugShowCheckedModeBanner: false,
      // Pass the light and dark themes, generated by our factory
      theme: getAppTheme(Brightness.light, accentColor),
      darkTheme: getAppTheme(Brightness.dark, accentColor),
      // Tell MaterialApp which theme to currently use based on our provider's state
      themeMode: themeMode,
      home: const HomePage(),
    );
  }
}
